### ISSUE TITLE
Querying signing-infos for genesis validators outputs the struct with empty address field

### ISSUE THREAD

**Issue by puneet2019** [cosmos/gaia#2801] opened 2023-11-08 08:46 UTC
## Summary of Bug
Querying signing-info for genesis validators outputs the struct with empty address field. 

## Version
Latest mainnet, v13

## Steps to Reproduce
i guess validators with startheight: 0 have no address mentioned in signing-info ( genesis validators? )
checked for figment: 
`gaiad q staking validator cosmosvaloper1hjct6q7npsspsg3dgvzk3sdf89spmlpfdn6m9d --node https://cosmos-rpc.polkachu.com:443`

`gaiad q slashing signing-info '{"@type":"/cosmos.crypto.ed25519.PubKey","key":"n9bW9hmvwSwm/AnJtDwZNGA+2RSoQsfoMFsc2Rrb0vY="}' --node https://cosmos-rpc.polkachu.com:443`
```
{"address":"","start_height":"0","index_offset":"21165260","jailed_until":"1970-01-01T00:00:00Z","tombstoned":false,"missed_blocks_counter":"22"}
```

for post genesis validators - created using create-validator command. 
`gaiad q staking validator cosmosvaloper1udpsgkgyutgsglauk9vk9rs03a3skc62gup9ny --node https://cosmos-rpc.polkachu.com:443`

`gaiad q slashing signing-info '{"@type":"/cosmos.crypto.ed25519.PubKey","key":"idewuO7ku3PO7LWarS4WNUPvvAZVgOTYMbyPqtcltlg="}' --node https://cosmos-rpc.polkachu.com:443`
```
{"address":"cosmosvalcons19f07eunv876rgf4vdv7mtzj6h3vqpu4qtedw05","start_height":"231548","index_offset":"15623695","jailed_until":"1970-01-01T00:00:00Z","tombstoned":false,"missed_blocks_counter":"0"}
```

Is this a bug? 

Not a blocking bug, because it outputs correct information for singular signing-info query just that the address is missing. 
And if one wants to query `all signing-infos` so that one can match them with `all validators`, it becomes impossible.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment] 2023-11-09 17:29
@puneet2019 Thanks for opening the issue. I believe though that this is a duplicate of https://github.com/cosmos/gaia/issues/1734. Could you please confirm?

**Comment by puneet2019** [comment] 2023-11-10 06:16
@mpoke  Ah yes! it is. it seems so old, any idea if it will ever be taken up?

**Comment by puneet2019** [comment] 2023-11-10 06:26
i believe
```
		keepers.SlashingKeeper.IterateValidatorSigningInfos(ctx,
			func(addr sdk.ConsAddress, info slashingtypes.ValidatorSigningInfo) bool {
				if info.Address == "" {
					info.Address = addr.String()
				}
				keepers.SlashingKeeper.SetValidatorSigningInfo(ctx, addr, info)
				return false
			})
```
in any upgrade instruction should do the job?

**Comment by mpoke** [comment] 2023-11-14 09:31
> any idea if it will ever be taken up?

@puneet2019 Not sure. It's not high on our priority list as we are not aware of it being an issue for users. If it's something that you need, please let us know so we can increase the priority.

I'll close this issue as a duplicate. Let's move the discussion to https://github.com/cosmos/gaia/issues/1734.

**Closed as completed by mpoke** 2023-11-14 09:31 UTC
Labels: type: bug, status: waiting-triage

**Comment by puneet2019** [comment] 2023-11-16 12:06
yes @mpoke https://github.com/cosmos/gaia/issues/1734#issuecomment-1555879910
this seems important enough, we could be querying all validators and matching with all-signing infos.
But it to do it in a loop for all 180 on archival node is quite expensive.
