### ISSUE TITLE
codespace sdk code 2::tx parse error

### ISSUE THREAD

**Issue by xihucuyu888** [cosmos/gaia#3014] opened 2024-03-21 03:00 UTC
## Summary of Bug

cannot parse some txs after upgrade to v15

## Version
v15

## Steps to Reproduce

/cosmos/tx/v1beta1/txs/FC4F5CC29C6DB6566FAD7FC42726AF3D7EB0BAAC678F871065C11FD89E1EE5D0

{
    "code": 2,
    "message": "codespace sdk code 2: tx parse error: no concrete type registered for type URL /cosmos.authz.v1beta1.MsgRevoke against interface *tx.TxExtensionOptionI",
    "details": []
}

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment] 2024-03-25 15:46
Related and duplicate of #3016.

Closing in favor of #3016.

**Closed as completed by MSalopek** 2024-03-25 15:46 UTC
Labels: type: bug, status: waiting-triage
