### ISSUE TITLE
unable to claim rewards from a validator

### ISSUE THREAD

**Issue by dicadotrade** [cosmos/gaia#1136] opened 2021-12-30 20:47 UTC
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nooomski** [comment] 2022-01-03 11:13
Hi, thanks for posting this issue. Can you please elaborate a bit more on the problem? We need more info to be able to reproduce and test this issue. Thanks!

**Comment by dicadotrade** [comment] 2022-01-03 19:34
This is the error message that appears when I try to claim my rewards via ledger app.


The server could not handle your request. Please try again later or contact Ledger Support. API HTTP 501

The validator is “GAME”

Thanks

**Comment by nooomski** [comment] 2022-01-04 11:17
This seems to be a Ledger issue due to the recent Vega update. Please keep track of this [notice](https://support.ledger.com/hc/en-us/articles/360013713840-Cosmos-ATOM-?docs=true) to see when this is fixed and contact them if you're still running into issues.

I'm going to close this issue as this is not something we can solve on the Gaia repo.

**Closed as completed by nooomski** 2022-01-04 11:17 UTC
Labels: more-info-needed

**Comment by yaruwangway** [comment] 2022-01-04 11:40
> 

I tried to withdraw reward from vega-testnet which is using the same version binary that the cosmoshub is running now. I am able to withdraw reward. So it is probably not cosmoshub's issue. 😁

**Comment by dicadotrade** [comment] 2022-01-04 12:30
Thank you very much.
I solved the issue reclaiming my rewards via keplr wallet.

Adolfo Dicuonzo

**Comment by glnro** [comment] 2022-01-04 12:57
> > 
> 
> I tried to withdraw reward from vega-testnet which is using the same version binary that the cosmoshub is running now. I am able to withdraw reward. So it is probably not cosmoshub's issue. 😁

Yes, this is an issue with ledger, for future reference, here's the [blog post](https://support.ledger.com/hc/en-us/articles/4414105534481-Cosmos-Vega-Upgrade?support=true) they published with a temporary workaround.
