### ISSUE TITLE
Api server does not work.

### ISSUE THREAD

**Issue by Spoiledpay** [cosmos/gaia#1541] opened 2022-06-17 14:42 UTC
## Summary of Bug

Once configured in App.toml and enabled with true. I noticed that the API server reports that it is not ready. Does anything additional need to be done for it to work?

## Version

gaia-7.0.2

## Steps to Reproduce
gaia start

http://localhost:1317/

{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]
}

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by okwme** [comment] 2022-07-04 14:56
hello,
this is actually expected behaviour while understandably confusing.
the reason is because the server is likely running while the root does not serve anything.
to confirm it is running please check: `https://localhost:1317/node_status`
please confirm whether this addressed your issue in the next week or we'll close the issue as resolved.
thank you

**Comment by okwme** [comment] 2022-07-25 15:33
closing issue with no reply

**Closed as completed by okwme** 2022-07-25 15:33 UTC
Labels: more-info-needed
