### ISSUE TITLE
v11.0.0-rc0 panic

### ISSUE THREAD

**Issue by tblkoff** [cosmos/gaia#2658] opened 2023-07-18 18:26 UTC
## Summary of Bug

Testnet Node panic after update from 10.0.2 to 11.0.0-rc0 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17f6bf4]

goroutine 121 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7ffc99dc7e34, 0xb}, 0xc00125a870, {0x266f920, 0xc001313df0}, {0x2691f90, 0xc001067be0}, 0xc001364390, {0x26694a0, 0xc000502c40}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/x/upgrade/abci.go:38 +0x1014
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2683f68, 0xc000058038}, {0x2691bd0, 0xc001674a00}, {{0xb, 0x0}, {0xc0011e0438, 0x11}, 0x1032b54, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/types/module/module.go:491 +0x1db
github.com/cosmos/gaia/v11/app.(*GaiaApp).BeginBlocker(...)
	github.com/cosmos/gaia/v11/app/app.go:235
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc00b6be3e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0011e0438, 0x11}, 0x1032b54, {0x39a73193, ...}, ...}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/baseapp/abci.go:177 +0x97b
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc00b6be3e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0011e0438, 0x11}, 0x1032b54, {0x39a73193, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.27/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc00b6be3e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0011e0438, 0x11}, 0x1032b54, {0x39a73193, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.27/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2684da0?, 0xc005e40480}, {0x268bf00, 0xc00051d5b0}, 0xc0030ca5a0, {0x26935c8, 0xc00923ba40}, 0x1032b53?)
	github.com/tendermint/tendermint@v0.34.27/state/execution.go:307 +0x51d
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc002f52b10, 0x8}}, {0xc00a65b9f8, 0x11}, 0x89dbae, 0x1032b53, {{0xc00b42bd20, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000503500, 0x0)
	github.com/tendermint/tendermint@v0.34.27/blockchain/v0/reactor.go:400 +0xbda
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.27/blockchain/v0/reactor.go:112 +0x7a

## Version

v11.0.0-rc0
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment] 2023-07-19 07:57
Hi, can you tell us more details, what's the the panic height, you see "upgrade" log before you swap binary from v10 to v11 ?

**Comment by tblkoff** [comment] 2023-07-19 08:36
HI! This is all that i have:
```
Configuring state sync...
6:21PM INF starting node with ABCI Tendermint in-process
6:21PM INF service start impl=multiAppConn module=proxy msg={}
6:21PM INF service start connection=query impl=localClient module=abci-client msg={}
6:21PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
6:21PM INF service start connection=mempool impl=localClient module=abci-client msg={}
6:21PM INF service start connection=consensus impl=localClient module=abci-client msg={}
6:21PM INF service start impl=EventBus module=events msg={}
6:21PM INF service start impl=PubSub module=pubsub msg={}
6:21PM INF service start impl=IndexerService module=txindex msg={}
6:21PM INF Found local state with non-zero height, skipping state sync
6:21PM INF ABCI Handshake App Info hash="�Q`N�f�\x05\x16e��R��}�+[�&�{�������0�" height=16984915 module=consensus protocol-version=0 software-version=v11.0.0-rc0
6:21PM INF ABCI Replay Blocks appHeight=16984915 module=consensus stateHeight=16984915 storeHeight=16984915
6:21PM INF Completed ABCI Handshake - CometBFT and App are synced appHash="�Q`N�f�\x05\x16e��R��}�+[�&�{�������0�" appHeight=16984915 module=consensus
6:21PM INF Version info abci=0.17.0 block=11 cmtbft_version=0.34.29 commit_hash= p2p=8
6:21PM INF This node is not a validator addr=38D4855A10A759E355285499E4AB4248D79969E4 module=consensus pubKey=Sm/fk/Vvly8s0waWgR8bIw7RVMtklxjy/mUBgh4i+kg=
6:21PM INF P2P Node ID ID=dc16f4d443af10e4975890bbc6015186fb0f29b7 file=/root/.gaia/config/node_key.json module=p2p
6:21PM INF Adding persistent peers addrs=[] module=p2p
6:21PM INF Adding unconditional peer ids ids=[] module=p2p
6:21PM INF Add our address to book addr={"id":"dc16f4d443af10e4975890bbc6015186fb0f29b7","ip":"0.0.0.0","port":26656} book=/root/.gaia/config/addrbook.json module=p2p
6:21PM INF service start impl=Node msg={}
6:21PM INF Starting pprof server laddr=localhost:6060
6:21PM INF service start impl="P2P Switch" module=p2p msg={}
6:21PM INF service start impl=BlockchainReactor module=blockchain msg={}
6:21PM INF service start impl=BlockPool module=blockchain msg={}
6:21PM INF service start impl=ConsensusReactor module=consensus msg={}
6:21PM INF Reactor  module=consensus waitSync=true
6:21PM INF serve module=rpc-server msg={}
6:21PM INF service start impl=Evidence module=evidence msg={}
6:21PM INF service start impl=StateSync module=statesync msg={}
6:21PM INF service start impl=PEX module=pex msg={}
6:21PM INF service start book=/root/.gaia/config/addrbook.json impl=AddrBook module=p2p msg={}
6:21PM INF Saving AddrBook to file book=/root/.gaia/config/addrbook.json module=p2p size=13
6:21PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
6:21PM INF service start impl="Peer{MConn{82.100.58.103:26656} 39de2434a983feb64b6b3c4886d1959334f90591 out}" module=p2p msg={} peer={"id":"39de2434a983feb64b6b3c4886d1959334f90591","ip":"82.100.58.103","port":26656}
6:21PM INF service start impl=MConn{82.100.58.103:26656} module=p2p msg={} peer={"id":"39de2434a983feb64b6b3c4886d1959334f90591","ip":"82.100.58.103","port":26656}
6:21PM INF service start impl="Peer{MConn{141.94.138.48:26670} e24c86bde94769c902ef40085867d9a03df6df4c out}" module=p2p msg={} peer={"id":"e24c86bde94769c902ef40085867d9a03df6df4c","ip":"141.94.138.48","port":26670}
6:21PM INF service start impl=MConn{141.94.138.48:26670} module=p2p msg={} peer={"id":"e24c86bde94769c902ef40085867d9a03df6df4c","ip":"141.94.138.48","port":26670}
6:21PM INF service start impl="Peer{MConn{95.217.172.214:26110} 3818016f3f4594dc3ebfac25ce54c914d8026502 out}" module=p2p msg={} peer={"id":"3818016f3f4594dc3ebfac25ce54c914d8026502","ip":"95.217.172.214","port":26110}
6:21PM INF service start impl=MConn{95.217.172.214:26110} module=p2p msg={} peer={"id":"3818016f3f4594dc3ebfac25ce54c914d8026502","ip":"95.217.172.214","port":26110}
6:21PM INF service start impl="Peer{MConn{104.245.147.203:26656} 3e506472683ceb7ed75c1578d092c79785c27857 out}" module=p2p msg={} peer={"id":"3e506472683ceb7ed75c1578d092c79785c27857","ip":"104.245.147.203","port":26656}
6:21PM INF service start impl=MConn{104.245.147.203:26656} module=p2p msg={} peer={"id":"3e506472683ceb7ed75c1578d092c79785c27857","ip":"104.245.147.203","port":26656}
6:21PM INF service start impl="Peer{MConn{35.239.129.49:26656} 58c2741e699d44c866802a2bf45fe5f621acf36b out}" module=p2p msg={} peer={"id":"58c2741e699d44c866802a2bf45fe5f621acf36b","ip":"35.239.129.49","port":26656}
6:21PM INF service start impl=MConn{35.239.129.49:26656} module=p2p msg={} peer={"id":"58c2741e699d44c866802a2bf45fe5f621acf36b","ip":"35.239.129.49","port":26656}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17f6bf4]
```

**Comment by yaruwangway** [comment] 2023-07-19 09:00
it might be a data and binary version mismatch.  If you join the public testnet https://explorer.theta-testnet.polypore.xyz/proposals, you can see here, the testnet is on v10, not v11 yet. If you test locally, can let me know your steps. You should see "upgrade" log and experience node panic before you change to the new binary.

**Comment by yaruwangway** [comment] 2023-07-21 15:45
Hi @tblkoff, we tested upgrade to v11 and there is no issues, please let us know if you still experience this panic, otherwise, we will close this issue next week, you can always reopen if the problem is not solved.

**Closed as completed** 2023-07-27 14:35 UTC
Labels: more-info-needed, type: bug
